### Register new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "budi",
  "password": "secret",
  "name": "Budi"
}

### Login user
POST http://localhost:3000/api/users/_login
Content-Type: application/json

{
  "username": "budi",
  "password": "secret"
}

### Get user profile
GET http://localhost:3000/api/users/_current
Accept: application/json
Authorization: {{token}}

### Logout user
DELETE http://localhost:3000/api/users
Accept: application/json
Authorization: {{token}}

### Update user
PATCH http://localhost:3000/api/users/_current
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "Budio"
}

### Create link
POST http://localhost:3000/api/links
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "title": "golang",
  "url": "https://github.com/golang"
}

### Get detail link
GET http://localhost:3000/api/links/{{linkId}}
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

### Update link
PUT http://localhost:3000/api/links/{{linkId}}
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "title": "go",
  "url": "https://github.com/golang/go"
}

### Delete link
DELETE http://localhost:3000/api/links/{{linkId}}
Accept: application/json
Authorization: {{token}}