app:
  name: "go-linktree"

web:
  prefork: false
  port: 3000

log:
  level: 6

database:
    username: "root"
    password: "root"
    host: "localhost"
    port: 3306
    name: "go-linktree"
    pool:
      idle: 10
      max: 100
      lifetime: 300